labsoft/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from modulos.accounts.views import lista_usuarios, agregar_usuario, editar_usuario, delete_user, agregar_rol, \
    editar_rol, delete_rol

from django.conf import settings
from .views import home, logoutUser
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', logoutUser, name="logout"),
    path('', home, name="index"),

    # módulo compras
    path('modulos/compras/', include('modulos.compras.urls')),

    # módulo ventas
    path('modulos/ventas/', include('modulos.ventas.urls')),

    # módulo produccion
    path('modulos/produccion/', include('modulos.produccion.urls')),

    # módulo reportes
    path('modulos/reportes/', include('modulos.reportes.urls')),

    # #usuarios
    path('user/list/', lista_usuarios, name='list_user'),
    path('user/add/', agregar_usuario, name='add_user'),
    path('user/edit/<id>', editar_usuario, name='edit_user'),
    path('user/delete/<id>', delete_user, name="delete_user"),

    path('rol/add/', agregar_rol, name='add_rol'),
    path('rol/edit/<id>/', editar_rol, name='editar_rol'),
    path('rol/delete/<id>/', delete_rol, name='delete_rol')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modulos/ventas/urls.py
from django.urls import path
from .views import *

app_name='ventas'

urlpatterns = [
    # Clientees
    path('clientes/list/', ClienteListView.as_view(), name='cliente_list'),
    path('clientes/add/', ClienteCreateView.as_view(), name='cliente_add'),
    path('clientes/edit/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_edit'),
    path('clientes/del/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_del'),

    path('facturas/add/', FacturaVentaCreateView.as_view(), name='factura_add'),
    path('facturas/add/<int:pedidoid>/', FacturaVentaCreateView.as_view(), name='factura_add_pedido'),

    path('facturas/list/', FacturaVentaListView.as_view(), name='factura_list'),
    path('facturas/edit/<int:pk>/', FacturaVentaUpdateView.as_view(), name='factura_edit'),
    path('facturas/del/<int:pk>/', FacturaVentaDeleteView.as_view(), name='factura_del'),
    path('facturas/invoice/pdf/<int:pk>/', FacturaPdfView.as_view(), name='factura_invoice_pdf'),

    path('pedidos/add/', PedidoCreateView.as_view(), name='pedido_add'),
    path('pedidos/list/', PedidoListView.as_view(), name='pedido_list'),
    path('pedidos/edit/<int:pk>/', PedidoUpdateView.as_view(), name='pedido_edit'),
    path('pedidos/del/<int:pk>/', PedidoDeleteView.as_view(), name='pedido_del'),



]

modulos/ventas/models.py
from django.db import models
from django.db.models.aggregates import Sum
from modulos.produccion.models import Producto
from django.forms import model_to_dict

ESTADOS_PEDIDOS = [
    ('PENDIENTE', 'Pendiente'),
    ('CANCELADO', 'Cancelado'),
    ('FINALIZADO', 'Finalizado'),
]


ESTADOS_FACTURA = [
    ('PENDIENTE', 'Pendiente'),
    ('CANCELADO', 'Cancelado'),
    ('FINALIZADO', 'Finalizado'),
]

# Create your models here.
class VentasConf(models.Model):
    iva_porc = models.FloatField(default=0.1)
    calc_iva = models.IntegerField(default=11)


TIPO_IVA = [
    ('IVA5', '5%'),
    ('IVA10', '10%'),
    ('EXENTA', 'Exenta')
]
# Modelo de Cliente.
class Cliente (models.Model):
    ruc = models.CharField(max_length=15, unique=True)
    cedula = models.CharField(max_length=15, unique=True, blank=True)
    nombre = models.CharField(max_length=50, blank=True)
    apellido = models.CharField(max_length=50, blank=True)
    razon_social = models.CharField(max_length=100, blank=True)
    telefono = models.CharField(max_length=20,blank=True)
    email = models.CharField(max_length=100, blank=True)
    direccion = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)

    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['nombre'] = self.nombre
        item['ruc'] = self.ruc
        item['apellido'] = self.apellido
        item['razon_social'] = self.razon_social
        item['cedula'] = self.cedula
        return item

    class Meta():
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"


class Cobro(models.Model):
    metodo_cobro = models.CharField(max_length=100)
    descripcion = models.TextField()
    medio_cobro = models.TextField()
    cantidad_cuotas=models.IntegerField(default=1)

    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['tipo_cobro'] = self.metodo_cobro
        item['medio_cobro']=self.medio_cobro
        item['cantidad_cuotas'] = self.cantidad_cuotas
        return item
    class Meta:
        verbose_name = "Cobro"
        verbose_name_plural = "Cobros"


class DatosFacturacion(models.Model):
    punto_venta= models.TextField()
    sucursal=models.TextField()
    timbrado_actual = models.TextField()
    inicio_timbrado=models.DateField()
    vencimiento_timbrado=models.DateField()
    numeracion_actual=models.IntegerField()

    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['punto_venta'] = self.punto_venta
        item['numeracion_actual'] = self.numeracion_actual
        item['sucursal'] = self.sucursal
   
        return item

    class Meta:
        verbose_name = "Datos Facturacion"
        verbose_name_plural = "Datos facturaciones"


class Timbrado(models.Model):
    timbrado_actual = models.TextField()
    inicio_timbrado=models.DateField()
    vencimiento_timbrado=models.DateField()


    class Meta:
        verbose_name = "Timbrado Facturacion"
        verbose_name_plural = "Timbrados"


class PuntoVenta (models.Model):
    codigo = models.CharField(max_length=15, unique=True)
    numero=  models.IntegerField(blank=False)


    def __str__(self):
        return '%s %s' % (self.codigo, self.numero)

    def toJSON(self):
        item = model_to_dict(self)
        item['numero'] = self.numero
        return item

    class Meta():
        verbose_name = "Punto Venta"
        verbose_name_plural = "Puntos Ventas"
        
class FacturaVenta(models.Model):
    nro_factura = models.CharField(max_length=20, blank=False)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    tipo_venta = models.CharField(max_length=200, blank=True)
    monto_iva1 = models.DecimalField(default=0.00, decimal_places=2, max_digits=9)  # 5%
    monto_iva2 = models.DecimalField(default=0.00, decimal_places=2, max_digits=9)  # 10% preguntar si esta bien
    total = models.FloatField(default=0)
    estado=models.CharField(max_length=200, blank=True)
    exenta = models.DecimalField( default=0.00, decimal_places=2, max_digits=9)
    fecha_emision = models.DateField()
    cobro = models.ForeignKey(Cobro, on_delete=models.PROTECT)
    punto_venta=models.ForeignKey(PuntoVenta, on_delete=models.PROTECT,default=1)
 

    def __str__(self):
        return 'Nro Factura: %s - Cliente: %s' % (self.nro_factura, self.cliente)
    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['nro_factura'] = self.nro_factura
        item['cliente'] = self.cliente.razon_social
        item['cliente_ruc']=self.cliente.ruc
        item['fecha_emision'] = self.fecha_emision
        item['estado'] = self.estado
        item['total'] = self.total
        item['tipo_venta'] = self.tipo_venta
        item['cobro_id']=self.cobro.id
        return item
    def obtener_fecha(self):
        print 
        return (self.fecha_emision.strftime("%d/%m/%Y"))
        
    def obtener_total(self):
        return int(self.total)
    def obtener_montoiva1(self):
        return round(self.monto_iva1)
    def obtener_montoiva2(self):
        return round(self.monto_iva2)
    def obtener_gravada_5(self):
        grabada5 = 0
        det = FacturaVentaDetalle.objects.filter(factura_id=self.id)
        for d in det:
            if d.producto.tasa_iva == 5:
                grabada5 += d.cantidad * d.precio
        return round(grabada5)
    def obtener_gravada_10(self):
        grabada10 = 0
        det = FacturaVentaDetalle.objects.filter(factura_id=self.id)
        for d in det:

            if d.producto.tasa_iva == 10:
                grabada10 += d.cantidad * d.precio
        return round(grabada10)
    def obtener_sin_iva(self):
            return int(self.total)-int(self.monto_iva1) -int(self.monto_iva2)-int(self.exenta)
    def obtener_exenta(self):
            return round(self.exenta)
    def obtener_timbrado(self):
        punto_venta=PuntoVenta.objects.get(id=self.punto_venta_id)
        datos=DatosFacturacion.objects.get(punto_venta=punto_venta.codigo)
        return (datos.timbrado_actual)


    class Meta:
        verbose_name = 'FacturaVenta'
        verbose_name_plural = 'Facturas'
        ordering = ['id']


class FacturaVentaDetalle(models.Model):
    factura = models.ForeignKey(FacturaVenta, on_delete=models.CASCADE)
    producto= models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)
    precio = models.DecimalField(default=0.00, decimal_places=2, max_digits=9)
    def obtener_subtotal(self):
        return int(self.cantidad)*int(self.precio)

    def obtener_total(self):
        return int(self.cantidad)*int(self.precio)

    def obtener_precio(self):
        return round(self.precio)
    class Meta:
        ordering = ['id']




class Cuota(models.Model):
    cobro = models.ForeignKey(Cobro, on_delete=models.CASCADE)
    estado = models.CharField(max_length=100)
    nro_cuota=models.IntegerField(default=1)
    fecha_vencimiento = models.DateField()
    fecha_pago_cuota = models.DateField(null=True)
    monto_cuota=models.IntegerField(default=0)

    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['cobro_id'] = self.cobro.id
        item['nro_cuota'] = self.nro_cuota
        item['estado'] = self.estado
        item['fecha_vencimiento'] = self.fecha_vencimiento
        item['fecha_pago'] = self.fecha_pago_cuota
        item['monto_cuota'] = self.monto_cuota
        return item
    class Meta:
        verbose_name = "Cuota"
        verbose_name_plural = "Cuotas"


# Create your models here.
class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha_pedido = models.DateField()
    fecha_entrega = models.DateField(null=True)
    estado = models.CharField(max_length=100, choices=ESTADOS_PEDIDOS)
    total = models.IntegerField(default=0)
    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['cliente_id'] = self.cliente.id
        item['cliente'] = self.cliente.razon_social
        item['cliente_ruc']=self.cliente.ruc
        item['estado'] = self.estado
        item['total'] = self.total
        return item
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'



class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(blank=False)
    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['codigo_producto'] = self.producto.codigo_producto
        item['descripcion_producto']=self.producto.nombre
        item['cantidad'] = self.cantidad
        item['precio'] = self.producto.precio
        item['total'] = self.producto.precio * self.cantidad
        return item
    class Meta:
        ordering = ['id']

modulos/ventas/old module/clientes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .forms import ClienteForm
from .models import Cliente
from django.contrib import messages


# Create your views here.
@login_required()
@permission_required('clientes.add_cliente', raise_exception=True)
def agregar_cliente(request):
    form = ClienteForm
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = ClienteForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, "El cliente ha sido agregado correctamente!")
            return redirect('/cliente/list/')

    context = {'form': form}
    return render(request, 'agregar_cliente.html', context)


@login_required()
@permission_required('clientes.change_cliente', raise_exception=True)
def editar_cliente(request, id):
    cliente = Cliente.objects.get(id=id)
    form = ClienteForm(instance=cliente)
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = ClienteForm(request.POST, instance=cliente)
        if not form.has_changed():
            messages.info(request, "No ha hecho ningun cambio")
            return redirect('/cliente/list/')
        if form.is_valid():
            cliente = form.save(commit=False)
            cliente.save()
            # messages.success(request, "El cliente ha sido editado correctamente!")
            messages.add_message(request, messages.SUCCESS, 'El Cliente se ha editado correctamente!')
            return redirect('/cliente/list/')

    context = {'form': form}
    return render(request, 'editar_cliente.html', context)


@login_required()
@permission_required('clientes.delete_cliente',raise_exception=True)
def delete_cliente(request, id):
    cliente = Cliente.objects.get(id=id)
    cliente.delete()
    return redirect('/cliente/list/')


@login_required()
@permission_required('clientes.view_cliente', raise_exception=True)
def lista_cliente(request):
    clientes = Cliente.objects.all()
    context = {'clientes': clientes}
    return render(request, 'lista_cliente.html', context)

modulos/ventas/old module/pagos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from .forms import PagoForm,PagoCuotaForm
from .models import Pago,PagoCuota
import datetime

# Create your views here.

@login_required()
@permission_required('pagos.add_pago', raise_exception=True)
def registrar_pago(request):
    form = PagoForm
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = PagoForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, "El pago ha sido registrado correctamente!")
            generar_cuotas(form)
            return redirect('/pago/list/')
    context = {'form': form}
    return render(request, 'registrar_pago.html', context)


@login_required()
@permission_required('pagos.change_pago', raise_exception=True)
def editar_pago(request, id):
    pago = Pago.objects.get(id=id)
    form = PagoForm(instance=pago)
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = PagoForm(request.POST, instance=pago)
        if not form.has_changed():
            messages.info(request, "No ha hecho ningun cambio")
            return redirect('/pago/list/')
        if form.is_valid():
            pago = form.save(commit=False)
            pago.save()
            # messages.success(request, "El cliente ha sido editado correctamente!")
            messages.add_message(request, messages.SUCCESS, 'El pago se ha editado correctamente!')
            return redirect('/pago/list/')
        else:
            messages.error(request, form.errors)

    context = {'form': form}

    return render(request, 'editar_pago.html', context)


@login_required()   
def editar_cuota(request, id):
    cuota = PagoCuota.objects.get(id=id)
    form = PagoCuotaForm(instance=cuota)
    if request.method == 'POST':
        cuota.estado=request.POST['estado']
        cuota.fecha_pago=datetime.date.today()
        cuota.save()
        pendientes=PagoCuota.objects.filter(id_pago_id=form.instance.id_pago_id).filter(estado='PENDIENTE').count()
        if pendientes==0:
            pago=Pago.objects.get(id=form.instance.id_pago_id)
            pago.estado='FINALIZADO'
            pago.save()
        messages.add_message(request, messages.SUCCESS, 'La cuota se ha editado correctamente!')
        return redirect('/pago/list')
       

    context = {'form': form}
    return render(request, 'editar_cuota.html', context)

@login_required()
@permission_required('pagos.delete_pago', raise_exception=True)
def delete_pago(request, id):
    pago= Pago.objects.get(id=id)
    pago.delete()
    return redirect('/pago/list/')


@login_required()
@permission_required('pagos.view_pago', raise_exception=True)
def lista_pagos(request):
    pagos = Pago.objects.all()
    context = {'pagos': pagos}
    return render(request, 'lista_pagos.html', context)

@login_required()
def lista_cuotas(request,id):
    cuotas = PagoCuota.objects.filter(id_pago_id=id)
    context = {'cuotas': cuotas}
    return render(request, 'lista_cuotas.html', context)



def generar_cuotas(form):
    dias=0
    for c in range(form.instance.cantidad_cuotas):
        cuota=PagoCuota()
        cuota.id_pago_id=form.instance.id
        cuota.estado='PENDIENTE'
        dias=dias+30
        cuota.fecha_vencimiento=datetime.date.today()+datetime.timedelta(days=dias)
        cuota.monto_cuota=(form.instance.monto_total)/(form.instance.cantidad_cuotas)
        cuota.save()

modulos/ventas/templates/facturas/factura_invoice.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style>
    .img-invoice {
        width: 50px;
        text-align: center;
        margin: 0 auto;
    }

    .head {
        text-align: center;
        text-transform: uppercase;
    }

    #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }

    .text-center{
        text-align: center;
    }
</style>
<body>
    
<img src="{{ icon }}" class="img-invoice">
<table border="1" style="width: 300px;">
    <tbody>
    <tr style="height: 164px;">
    <td style="width: 415.172px; height: 164px;">
    <h1 style="text-align: center;"><strong>LABORATORIOS OCAMPOS</strong></h1>
    <h2 style="text-align: center;"><strong>SOCIEDAD DE RESPONSABILIDAD LIMITADA</strong></h2>
    <h2 style="text-align: center;"><strong>Produccion de Cosméticos.</strong></h2>
    <h2 style="text-align: center;">Dr. Waldino Lovera c/ Juan Motta N° 581. Tel.: (021) 584 585.</h2>
    <h3 style="text-align: center;"><strong>SAN LORENZO, PARAGUAY</strong></h3>
    <p></p>
    </td>
    <td style="width: 323.828px; height: 164px; text-align: center;">
    <p><strong></strong></p>
    <h1><p><strong>TIMBRADO N° {{ datos_facturacion.timbrado_actual }}</strong></p></h1>

    <h1><p><strong>RUC 80006177-2</strong></p></h1>
    <h1><p><strong>FACTURA</strong></p></h1>

    <h1><p style="text-align: center;"><strong>{{ factura.nro_factura }}</strong></p></h1>
    <p></p>
    <p></p>
    <p></p>
    </td>
    </tr>
    <tr style="height: 85px;">
    <td style="width: 415.172px; height: 85px;" colspan="2">
    <h3 style="text-align: center;"><strong></strong></h3>
        <b>&nbsp; &nbsp;FECHA DE EMISION:</b> {{ factura.fecha_emision}}<br>
        <b>&nbsp; &nbsp; &nbsp;CONDICION DE VENTA:</b> {{ factura.cobro.metodo_cobro}}<br>

        <b>&nbsp; &nbsp;&nbsp;NOMBRE O RAZON SOCIAL:</b> {{ factura.cliente.razon_social|upper }}<br>
        <b>&nbsp; &nbsp;&nbsp;RUC:</b> {{ factura.cliente.ruc }}<br>
        <b>&nbsp; &nbsp;&nbsp;DIRECCION:</b> {{ factura.cliente.direccion}}<br>

    </td>
    </tr>
    </tbody>
    </table>
    <table style="width: 345px;">
        <tbody>
        
        </tbody>
        </table>
<table id="invoice">
    <thead>
    <tr>
        <th style="width: 10%;">CANT</th>
        <th style="width: 15%;">PRECIO UNITARIO</th>
        <th style="width: 20%;">CODIGO</th>
        <th style="width: 40%;">PRODUCTO</th>
        <th style="width: 40%;">TIPO IVA</th>

        <th style="width: 10%;">TOTAL</th>
    </tr>
    </thead>
    <tbody>
    {% for d in factura.facturaventadetalle_set.all %}
        <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %}>
            <td class="text-center" id="cantidadProducto">{{ d.cantidad }}</td>
            <td class="text-center" id="precioProducto">Gs. {{ d.obtener_precio}}</td>
            <td>{{ d.producto.codigo_producto }}</td>
            <td>{{ d.producto.nombre }}</td>
            <td>{{ d.producto.tasa_iva }}%</td>
            <td style="text-align: right;" id="subtotalProducto">Gs. {{ d.obtener_subtotal }}</td>
        </tr>
    {% endfor %}
    <tr style="border-top: 1px solid black; padding-top: 4px;">
        <td colspan="4"><b>SUBTOTAL</b></td>
        <td style="text-align: right">Gs. {{ factura.obtener_total }}</td>
    </tr>
    <tr style="padding-top: 0px;">
        <td colspan="4"><b>IVA 10%</b></td>
        <td style="text-align: right">Gs. {{ factura.obtener_montoiva1 }}</td>
    </tr>
    <tr style="padding-top: 0px;">
        <td colspan="4"><b>IVA 5%</b></td>
        <td style="text-align: right">Gs. {{ factura.obtener_montoiva2 }}</td>
    </tr>
    <tr style="padding-top: 0px;">
        <td colspan="4"><b>TOTAL A PAGAR</b></td>
        <td style="text-align: right">Gs. {{ factura.obtener_total }}</td>
    </tr>
    </tbody>
</table>
<table style="margin-top: 250px;">
    <thead>
    <tr>
        <th>****GRACIAS POR SU COMPRA****</th>
    </tr>
    <tr>
        <th>NOSE ACEPTAN CAMBIOS NI DEVOLUCIONES</th>
    </tr>
    </thead>
</table>
</body>
</html>

modulos/ventas/templates/facturas/facturas_list.html
{% extends 'base.html' %}

{% load static %}

{% block navbar %}
    {% include 'home/navbar.html' %}
{% endblock navbar %}

{% block head-app %}
    <div>
        <h1><i class="fas fa-atom"> </i> {{ title }}</h1>
        <p>Sistema de Gestion - Labsoft</p>
    </div>
{% endblock %}

{% block head %}
    <style>
        #Table td, th {
            vertical-align: inherit;
            padding: 0.4rem;
        }
    </style>
{% endblock %}

{% block sidebar %}
    {% include 'home/sidebar.html' %}
{% endblock sidebar %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ route }}">{{ title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">
                    <div class="table-responsive">
                            {% if perms.ventas.add_facturaventa %}
                           
                                <a class="btn btn-success p-2" href="{% url 'ventas:factura_add' %}"
                                           title="Editar">
                                            <i class="fas fa-plus"></i>
                                        </a>
                                {% csrf_token %}
                            {% endif %}
                        <div style="text-align: center;">
                            <h4 style="font-size: large; margin-bottom: 0" class="tile-title">{{ subtitle }}</h4>
                        </div>
                        <table class="table table-hover table-bordered" id="facturaTable" style="max-width: 100%; width: 100%">
                            <thead>
                            <tr style="font-size: 0.7rem">
                                <th>Número Factura</th>
                                <th>Cliente</th>
                                <th>Fecha de Emisión</th>
                                <th>Estado</th>
                                <th>Total Factura</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr style="font-size: 0.75rem;">
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td style="text-align: center;">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    </div>

<div class="modal fade" id="modalCobro" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b><i class="fas fa-shopping-cart"></i> Gestionar cuotas</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-bordered" id="cobroDet">
                    <thead>
                    <tr>
                        <th>Nro Cuota</th>
                        <th>Monto</th>
                        <th>Estado</th>
                        <th>Fecha vencimiento</th>
                        <th>Fecha pago</th>
                        <th>Acciones</th>

                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
       
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "js/functions/functions.js" %}"></script>
    <script type="text/javascript" src="{% static "js/ventas/index.js" %}"></script>
    <script>
        list_factura('/modulos/ventas/facturas/list/', '/modulos/ventas/facturas/edit/', '/modulos/ventas/facturas/del/', {{ perms.ventas.change_facturaventa | safe | lower}}, {{ perms.ventas.delete_facturaventa | safe | lower}});
    </script>
{% endblock %}