labsoft/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from modulos.accounts.views import lista_usuarios, agregar_usuario, editar_usuario, delete_user, agregar_rol, \
    editar_rol, delete_rol

from django.conf import settings
from .views import home, logoutUser
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', logoutUser, name="logout"),
    path('', home, name="index"),

    # módulo compras
    path('modulos/compras/', include('modulos.compras.urls')),

    # módulo ventas
    path('modulos/ventas/', include('modulos.ventas.urls')),

    # módulo produccion
    path('modulos/produccion/', include('modulos.produccion.urls')),

    # módulo reportes
    path('modulos/reportes/', include('modulos.reportes.urls')),

    # #usuarios
    path('user/list/', lista_usuarios, name='list_user'),
    path('user/add/', agregar_usuario, name='add_user'),
    path('user/edit/<id>', editar_usuario, name='edit_user'),
    path('user/delete/<id>', delete_user, name="delete_user"),

    path('rol/add/', agregar_rol, name='add_rol'),
    path('rol/edit/<id>/', editar_rol, name='editar_rol'),
    path('rol/delete/<id>/', delete_rol, name='delete_rol')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modulos/produccion/urls.py
from django.urls import path
from .views import *

app_name='produccion'

urlpatterns = [
    # producto
    path('productos/list/', ProductoListView.as_view(), name='producto_list'),
    path('productos/add/', ProductoCreateView.as_view(), name='producto_add'),
    path('productos/edit/<int:pk>/', ProductoUpdateView.as_view(), name='producto_edit'),
    path('productos/del/<int:pk>/', ProductoDeleteView.as_view(), name='producto_del'),

    # equipo
    path('equipos/list/', EquipoListView.as_view(), name='equipo_list'),
    path('equipos/add/', EquipoCreateView.as_view(), name='equipo_add'),
    path('equipos/edit/<int:pk>/', EquipoUpdateView.as_view(), name='equipo_edit'),
    path('equipos/del/<int:pk>/', EquipoDeleteView.as_view(), name='equipo_del'),
    
    
    path('orden/list/', OrdenListView.as_view(), name='orden_list'),
    path('orden/add/', OrdenCreateView.as_view(), name='orden_add'),
    path('orden/edit/<int:pk>/', OrdenUpdateView.as_view(), name='orden_edit'),
    path('orden/del/<int:pk>/', OrdenDeleteView.as_view(), name='orden_del'),

    path('formula/add/', FormulaCreateView.as_view(), name='formula_add'),
    path('formula/edit/<int:pk>/', FormulaUpdateView.as_view(), name='formula_edit'),
    path('formula/list/', FormulaListView.as_view(), name='formula_list'),
    path('formula/del/<int:pk>/', FormulaDeleteView.as_view(), name='formula_del'),

]

modulos/produccion/models.py
from django.db import models
from django.forms import model_to_dict

from modulos.compras.models import MateriaPrima

TIPO_IVA = [
    ( 5,'IVA5',),
    ( 10,'IVA10'),
    (0,'EXENTA')
]
TIPO_ORDEN = [
    ( 'PENDIENTE','PENDIENTE'),
    ( 'EN PRODUCCION','EN PRODUCCION'),
    ('FINALIZADA','FINALIZADA')
]

UNIDAD_MEDIDA = [
    ( 'MILILITROS','Mililitros'),
    ( 'GRAMOS','Gramos'),
    ( 'LITROS','Litros'),
    ( 'KILOGRAMOS','Kilogramos'),
]
# Create your models here.


class Producto(models.Model):
    codigo_producto = models.CharField(max_length=50,unique=True)
    nombre = models.CharField(max_length=100, null=False)
    volumen = models.FloatField(blank=True, null=True, default=0)
    color = models.CharField(max_length=10, blank=True, default='')
    precio = models.FloatField()
    cantidad_contenido = models.FloatField(blank=True)
    tipo = models.CharField(max_length=10, blank=True, default='')
    tasa_iva= models.IntegerField(default=0,choices=TIPO_IVA)
    stock_inicial= models.IntegerField(default=0,blank=True)
    unidad_medida=models.CharField(max_length=100,default='Litros',choices=UNIDAD_MEDIDA)

    def __str__(self):
        return '%s %s' % (self.codigo_producto, self.nombre)
    
    def toJSON(self):
        item = model_to_dict(self)
        item['nombre'] = self.nombre
        item['precio'] = self.precio
        item['tipo'] = self.tipo
        item['tasa_iva'] = self.tasa_iva
        return item

    def obtener_cantidad_producida(self,mes,anho):
        cantidad_producida = 0 
        ordenes=OrdenElaboracion.objects.filter(estado='FINALIZADA',producto_id=self.id,fecha_emision__year=anho,fecha_emision__month=mes)
        for orden in ordenes:
             cantidad_producida =cantidad_producida + float(orden.cantidad_teorica) / ((orden.producto.cantidad_contenido) / float(1000))
        return int(cantidad_producida)

    def obtener_cantidad_vendida(self,mes,anho):
        from modulos.ventas.models import FacturaVenta, FacturaVentaDetalle
        cantidad_vendida = 0 
        facturas=FacturaVenta.objects.filter(fecha_emision__year=anho,fecha_emision__month=mes)
        for factura in facturas:
            for facturadetalle in FacturaVentaDetalle.objects.filter(factura_id=factura.id,producto_id=self.id):
                cantidad_vendida=cantidad_vendida+ facturadetalle.cantidad
        return cantidad_vendida
    def obtener_unidad_orden(self):
        if self.unidad_medida == 'MILILITROS':
            return 'LITROS'
        else:
            return 'KILOGRAMOS'
        

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'





class StockProductos(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad= models.IntegerField()


    def __str__(self):
        return '%s %s' % (self.producto, self.nombre)

    def obtener_dict(self):
        dict = {}
        dict['producto'] = self.producto
        dict['cantidad'] = self.cantidad

        return dict

    class Meta:
        verbose_name = 'StockProducto'
        verbose_name_plural = 'StockProductos'


class Equipo(models.Model):
    codigo= models.CharField(max_length=30, null=False,unique=True)
    nombre= models.CharField(max_length=150, blank=True)
    horas_utiles=models.IntegerField(default=100)
    horas_utilizadas=models.IntegerField(default=0,null=True,blank=True)
    ultimo_mantenimiento=models.DateField(blank=True,null=True)
    proximo_mantenimiento=models.DateField(blank=True,null=True)
    fecha_ingreso=models.DateField(blank=True,null=True)
    def __str__(self):
        return '%s %s' % (self.codigo, self.nombre)

    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['codigo'] = self.codigo
        item['nombre'] = self.nombre
        item['descripcion'] = self.nombre

        item['horas_utiles'] = self.horas_utiles
        item['horas_utilizadas'] = self.horas_utilizadas
        item['ultimo_mantenimiento']=''
        item['proximo_mantenimiento']=''
        item['fecha_ingreso']=''

        return item

    def obtener_porcentaje(self):
        return round((self.horas_utilizadas * 100)/self.horas_utiles)
    def obtener_estado(self):
        porcentaje= round((self.horas_utilizadas * 100)/self.horas_utiles)
        if (porcentaje<90):
            estado= 'Utilizable.'
        else:
            estado='Necesita mantenimiento.'
        
        return estado
    class Meta:
        verbose_name = 'Equipo'
        verbose_name_plural = 'Equipos'


class OrdenElaboracion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad_teorica = models.IntegerField()
    estado = models.CharField(max_length=15,choices=TIPO_ORDEN,default=TIPO_ORDEN[0])
    numero = models.IntegerField()
    fecha_emision = models.DateField()
    fecha_vigencia = models.DateField()
    elaborado_por = models.CharField(max_length=200)
    aprobado_por = models.CharField(max_length=200)
    verificado_por = models.CharField(max_length=200)
    descripcion_modificacion= models.CharField(max_length=100,default='Emision Inicial')


    def toJSON(self):
        item = model_to_dict(self)
        item['id']=self.id
        item['numero'] = self.numero
        item['estado'] = self.estado
        item['fecha_emision'] = self.fecha_emision
        item['fecha_vigencia'] = self.fecha_vigencia
        item['cantidad_teorica'] = self.cantidad_teorica
        item['producto'] = self.producto.nombre
     


        return item
    class Meta:
        verbose_name = 'Orden de Elaboración'
        verbose_name_plural = 'Ordenes de Elaboración'

    def __str__(self):
        return self.numero


class DetalleOrdenElaboracion(models.Model):
    orden = models.ForeignKey(OrdenElaboracion, on_delete=models.CASCADE)
    materia = models.ForeignKey(MateriaPrima, on_delete=models.CASCADE)
    inci= models.CharField(max_length=30)
    cantidad = models.FloatField()
    unidad_medida = models.CharField(max_length=30)


    class Meta:
        verbose_name = 'Detalle Orden de Elaboración'
        verbose_name_plural = 'Detalles de orden de elaboracion'

    def __str__(self):
        return self.orden


class EquipoOrdenElaboracion(models.Model):
    orden = models.ForeignKey(OrdenElaboracion, on_delete=models.CASCADE)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    horas_trabajo=models.IntegerField(default=0)
    class Meta:
        verbose_name = 'Equipo en Orden de Elaboración'
        verbose_name_plural = 'Equipos de orden de elaboracion'

    def __str__(self):
        return self.orden

class Formula(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad_teorica=models.FloatField(default=0)
    class Meta:
        verbose_name = 'Formula'
        verbose_name_plural = 'Formulas'

    def toJSON(self):
        item = model_to_dict(self)
        item['id'] = self.id
        item['producto'] = self.producto.nombre
        item['cantidad_teorica']=self.cantidad_teorica
        return item



    def __str__(self):
        return self.producto

class FormulaProducto(models.Model):
    formula=models.ForeignKey(Formula, on_delete=models.CASCADE,default=0)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    materia= models.ForeignKey(MateriaPrima, on_delete=models.CASCADE)
    cantidad= models.FloatField()
    cantidad_teorica=models.FloatField(default=0)
    
    class Meta:
        verbose_name = 'Formula'
        verbose_name_plural = 'Formula Productos'

    def toJSON(self):
        item = model_to_dict(self)
        item['producto_id'] = self.producto.id
        item['id'] = self.materia.id
        item['codigo']=self.materia.codigo
        item['inci']=self.materia.inci
        item['unidad_medida']=self.materia.um
        item['cantidad'] = self.cantidad
        item['descripcion'] = self.materia.descripcion
        item['cantidad_teorica']=self.cantidad_teorica

        return item
    def __str__(self):
        return self.orden

modulos/produccion/old module/equipos/forms.py
from django import forms
from .models import Equipo
from datetime import datetime

class EquipoForm(forms.ModelForm):
    class Meta():
        model = Equipo
        fields = '__all__'

        widgets = {
            'codigo_equipo' : forms.TextInput(attrs={'class': 'form-control'}),
            'nombre' : forms.TextInput(attrs={'class': 'form-control'}),

            'descripcion' : forms.TextInput(attrs={'class': 'form-control'}),
            'modelo' : forms.TextInput(attrs={'class': 'form-control'}),


            'estado': forms.Select(attrs={'class': 'form-control',
                                     'id': 'estado_select',
                                     'style': 'width: 100%',}),
            'costo' : forms.NumberInput(attrs={'class': 'form-control'}),
            'codigo_elaboracion' : forms.TextInput(attrs={'class': 'form-control'})

        }

modulos/produccion/old module/orden/forms.py
from datetime import datetime

from django import forms


# Create your froms here.
from modulos.produccion.orden.models import OrdenElaboracion


class OrdenForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'

    class Meta:
        model = OrdenElaboracion
        fields = '__all__'
        exclude = ['hora_inicio', 'hora_final']
        widgets = {
            'desc_producto': forms.Textarea(attrs={
                'class':'form-control'
            }),
            'fecha_emision': forms.DateInput(attrs={
                'class': 'form-control',
                'value': datetime.now().strftime('%d/%m/%Y')
            }),
        }

modulos/produccion/old module/equipos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from .forms import EquipoForm
from .models import Equipo


# Create your views here.

@login_required()
@permission_required('equipos.add_equipo', raise_exception=True)
def agregar_equipo(request):
    form = EquipoForm
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = EquipoForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, "El equipo ha sido registrado correctamente!")
            return redirect('/equipo/list/')

    context = {'form': form}
    return render(request, 'registrar_equipo.html', context)


@login_required()
@permission_required('equipos.change_equipo', raise_exception=True)
def editar_equipo(request, id):
    equipo = Equipo.objects.get(id=id)
    form = EquipoForm(instance=equipo)
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = EquipoForm(request.POST, instance=equipo)
        if not form.has_changed():
            messages.info(request, "No ha hecho ningun cambio")
            return redirect('/equipo/list/')
        if form.is_valid():
            equipo = form.save(commit=False)
            equipo.save()
            # messages.success(request, "El cliente ha sido editado correctamente!")
            messages.add_message(request, messages.SUCCESS, 'El equipo se ha editado correctamente!')
            return redirect('/equipo/list/')

    context = {'form': form}
    return render(request, 'editar_equipo.html', context)


@login_required()
@permission_required('equipos.delete_equipo', raise_exception=True)
def delete_equipo(request, id):
    equipo = Equipo.objects.get(id=id)
    equipo.delete()
    return redirect('/equipo/list/')


@login_required()
@permission_required('equipos.view_equipo', raise_exception=True)
def lista_equipos(request):
    equipos = Equipo.objects.all()
    context = {'equipos': equipos}
    return render(request, 'lista_equipos.html', context)

modulos/produccion/old module/orden/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect

# Create your views here.
from modulos.produccion.orden.forms import OrdenForm
from modulos.produccion.orden.models import OrdenElaboracion


@login_required()
@permission_required('orden.add_ordenelaboracion', raise_exception=True)
def agregar_orden(request):
    form = OrdenForm()
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = OrdenForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, "El orden ha sido agregado correctamente!")
            return redirect('/orden/list/')
        else:
            messages.error(request, form.errors)

    context = {'form': form}
    return render(request, 'agregar_orden.html', context)


@login_required()
@permission_required('orden.change_ordenelaboracion', raise_exception=True)
def editar_orden(request, id):
    print("Hola")
    orden = OrdenElaboracion.objects.get(id=id)
    form = OrdenForm(instance=orden)
    if request.method == 'POST':
        print("Imprimiendo POST: ", request.POST)
        form = OrdenForm(request.POST, instance=orden)
        if not form.has_changed():
            messages.info(request, "No ha hecho ningun cambio")
            return redirect('/orden/list/')
        if form.is_valid():
            orden = form.save(commit=False)
            orden.save()
            # messages.success(request, "El cliente ha sido editado correctamente!")
            messages.add_message(request, messages.SUCCESS, 'El Orden se ha editado correctamente!')
            return redirect('/orden/list/')
        else:
            messages.add_message(request, messages.ERROR, form.errors)

    context = {'form': form}
    return render(request, 'editar_orden.html', context)


@login_required()
@permission_required('orden.delete_ordenelaboracion',raise_exception=True)
def delete_orden(request, id):
    orden = OrdenElaboracion.objects.get(id=id)
    orden.delete()
    return redirect('/orden/list/')


@login_required()
@permission_required('orden.view_ordenelaboracion', raise_exception=True)
def lista_orden(request):
    orden = OrdenElaboracion.objects.all()
    context = {'ordenes': orden}
    return render(request, 'lista_orden.html', context)

modulos/produccion/templates/formulas/formulas_add.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
    {% include 'home/navbar.html' %}
{% endblock navbar %}

{% block head %}

    
    <link type="text/css" href="{% static "lib/bootstrap-touchspin-master/src/jquery.bootstrap-touchspin.css" %}"
          rel="stylesheet"/>
    <link href="{% static "lib/jquery-ui-1.12.1/jquery-ui.min.css" %}" rel="stylesheet"/>
 
    


{% endblock %}

{% block head-app %}
    <div>
        <h1><i class="fas fa-atom"> </i> Produccion</h1>
        <p>Sistema de Gestion - Labsoft</p>
    </div>
{% endblock %}

{% block sidebar %}
    {% include 'home/sidebar.html' %}
{% endblock sidebar %}

{% block content %}
<form method="post">
            {% csrf_token %}
        <div class="tile mb-4">
            <div class="row">
                <div class="col-lg-9" >
                    <div class="page-header">
                        <h5 class="mb-3 line-head" id="typography">Registrar Formula</h5>
                        <div class="row-lg-9">
                            
                            <div class="card" >
                                
                                <h6 class="card-header">Datos Formula</h6>
                                <div class="card-body">
                                    <input type="hidden" name="action" value="add">
                                    <div class="form-row">
                                   
                                        <div class="col">
                                            <label><strong>Producto:</strong></label>
                                            {{ form.producto }}                           
                                         </div>
                                           
                                        <div class="col">
                                            <label><strong>Cantidad Teorica: </strong></label>
                                            {{ form.cantidad_teorica }}   
                                                                 
                                         </div>
                                        <fieldset disabled>
                                        <div class="col">
                                            <label><strong>Unidad medida:</strong></label>
                                            <select class="form-control" id="unidad_medida">
                                                <option>Litros</option>
                                                <option>Kilogramos</option>

                                            </select>                                                                 
                                         </div>
                                        </fieldset>
                                        <button type="button" class="mb-2 py-0 btn btn-success btn-sm btnFormula"
                                        style="height: 25px; align-content: center">
                                        <label>Verificar existencia</label>
                                        </button>
                                        <div class="form-group">
                                           
                                        </div>
      
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
                </div>
            </div>
            <div class="form-group"></div>
            <div class="row">
                <div class="col-lg-9">
                    <div class="card">
                        <h6 class="card-header"> Materias Primas </h6>
                        <div class="card-body">
                            <div class="form-group">
                                <label> <strong> Buscar Materia Prima:</strong> </label>
                                <span class="input-group-append">
                                    <input type="text" class="form-control" id="search"
                                    placeholder="Ingrese una descripción de producto" autocomplete="off">
                                    <span class="input-group-append">
                                        <button type="button" class="btn btn-danger btn-flat">
                                            <i class="fas fa-times"></i></button>
                                    </span>                          
                                </span>
                            </div>
                            <div class="table-responsive">
                                <button type="button" class="mb-2 py-0 btn btn-danger btn-sm btnRemoveAll"
                                        style="height: 20px; align-content: center">
                                    <label>Eliminar todo</label>
                                </button>
                                <table class="table table-bordered"
                                       id="tblOrden" style="width: 100%;">
                                    <thead>
                                    <tr>
                                        <td>Cod</td>
                                        <td>Descripción</td>
                                        <td>INCI</td>
                                        <td>Cantidad</td>
                                        <td>Unidad de Medida</td>
                                        <td>Eliminar</td>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
   
                    </div>
                    

                </div>
             
         
            </div>
 
            <div class="tile-footer">
                <button type="submit" class="btn btn-primary" style="color: white"><i
                        class="fa fa-fw fa-lg fa-check-circle"></i>Registrar Formula
                </button>&nbsp;&nbsp;&nbsp;
                <a class="btn btn-secondary" href="{% url 'index' %}">
                    <i class="fa fa-fw fa-lg fa-times-circle"></i>Cancelar</a>
            </div>
        </div>
        </div>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static "lib/jquery-ui-1.12.1/jquery-ui.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/bootstrap-datepicker.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/select2.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/jquery.dataTables.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/dataTables.bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/datatable-es/dataTable-es.js" %} "></script>
    <script type="text/javascript" src="{% static "js/plugins/sweetalert.min.js" %}"></script>
    <script type="text/javascript"
            src="{% static "lib/bootstrap-touchspin-master/src/jquery.bootstrap-touchspin.js" %} "></script>
    <!--Lenguage español-->
    <script type="text/javascript" src="{% static "js/plugins/bootstrap-datepicker.es.js" %}"></script>
    <script type="text/javascript" src= {% static "js/functions/functions.js " %}></script>
    <script type="text/javascript" src= {% static "js/produccion/formsFormula.js" %}></script>
    <script>
 
        // Se removio el vents.list(); para calcular bien el iva en el editar. Revisar al final del archivo form.js se lo puso.
    </script>
{% endblock %}

modulos/produccion/templates/formulas/formulas_list.html
{% extends 'base.html' %}

{% load static %}

{% block navbar %}
    {% include 'home/navbar.html' %}
{% endblock navbar %}

{% block head-app %}
    <div>
        <h1><i class="fas fa-atom"> </i> {{ title }}</h1>
        <p>Sistema de Gestion - Labsoft</p>
    </div>
{% endblock %}

{% block head %}
    <style>
        #Table td, th {
            vertical-align: inherit;
            padding: 0.4rem;
        }
    </style>
{% endblock %}

{% block sidebar %}
    {% include 'home/sidebar.html' %}
{% endblock sidebar %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ route }}">{{ title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">
                    <div class="table-responsive">
                            {% if perms.produccion.add_formula %}
                           
                                <a class="btn btn-success p-2" href="{% url 'produccion:formula_add' %}"
                                           title="Agregar Formula">
                                            <i class="fas fa-plus"></i>
                                        </a>
                                {% csrf_token %}
                            {% endif %}
                        <div style="text-align: center;">
                            <h4 style="font-size: large; margin-bottom: 0" class="tile-title">{{ subtitle }}</h4>
                        </div>
                        <table class="table table-hover table-bordered" id="formTable" style="max-width: 100%; width: 100%">
                            <thead>
                            <tr style="font-size: 0.7rem">
                                <th>Producto</th>
                                <th>Cantidad Teorica</th>
                               
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr style="font-size: 0.75rem;">
                                    <td></td>
                                    <td></td>
                            
                                    <td style="text-align: center;">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    </div>


{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "js/functions/functions.js" %}"></script>
    <script type="text/javascript" src="{% static "js/produccion/index.js" %}"></script>
    <script>
        list_formula('/modulos/produccion/formula/list/', '/modulos/produccion/formula/edit/','/modulos/produccion/formula/del/', {{ perms.produccion.change_formula | safe | lower}}, {{ perms.produccion.delete_formula | safe | lower}});
    </script>
{% endblock %}